file_format: "1"
id: ergos1
name: Ergo S-1
type: shield
url: https://github.com/wizarddata/Ergo-S-1
requires:
  - pro_micro
exposes: [i2c_oled]
features:
  - keys
siblings:
  - ergos1_left
  - ergos1_right
